// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/0x0BSoD/newsMaker/internal/fetcher"
	"github.com/0x0BSoD/newsMaker/internal/model"
	"sync"
)

// Ensure, that ArticleStorageMock does implement fetcher.ArticleStorage.
// If this is not the case, regenerate this file with moq.
var _ fetcher.ArticleStorage = &ArticleStorageMock{}

// ArticleStorageMock is a mock implementation of fetcher.ArticleStorage.
//
//	func TestSomethingThatUsesArticleStorage(t *testing.T) {
//
//		// make and configure a mocked fetcher.ArticleStorage
//		mockedArticleStorage := &ArticleStorageMock{
//			LinkExistsFunc: func(ctx context.Context, link string) (bool, error) {
//				panic("mock out the LinkExists method")
//			},
//			StoreFunc: func(ctx context.Context, article model.Article) error {
//				panic("mock out the Store method")
//			},
//		}
//
//		// use mockedArticleStorage in code that requires fetcher.ArticleStorage
//		// and then make assertions.
//
//	}
type ArticleStorageMock struct {
	// LinkExistsFunc mocks the LinkExists method.
	LinkExistsFunc func(ctx context.Context, link string) (bool, error)

	// StoreFunc mocks the Store method.
	StoreFunc func(ctx context.Context, article model.Article) error

	// calls tracks calls to the methods.
	calls struct {
		// LinkExists holds details about calls to the LinkExists method.
		LinkExists []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Link is the link argument value.
			Link string
		}
		// Store holds details about calls to the Store method.
		Store []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Article is the article argument value.
			Article model.Article
		}
	}
	lockLinkExists sync.RWMutex
	lockStore      sync.RWMutex
}

// LinkExists calls LinkExistsFunc.
func (mock *ArticleStorageMock) LinkExists(ctx context.Context, link string) (bool, error) {
	if mock.LinkExistsFunc == nil {
		panic("ArticleStorageMock.LinkExistsFunc: method is nil but ArticleStorage.LinkExists was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Link string
	}{
		Ctx:  ctx,
		Link: link,
	}
	mock.lockLinkExists.Lock()
	mock.calls.LinkExists = append(mock.calls.LinkExists, callInfo)
	mock.lockLinkExists.Unlock()
	return mock.LinkExistsFunc(ctx, link)
}

// LinkExistsCalls gets all the calls that were made to LinkExists.
// Check the length with:
//
//	len(mockedArticleStorage.LinkExistsCalls())
func (mock *ArticleStorageMock) LinkExistsCalls() []struct {
	Ctx  context.Context
	Link string
} {
	var calls []struct {
		Ctx  context.Context
		Link string
	}
	mock.lockLinkExists.RLock()
	calls = mock.calls.LinkExists
	mock.lockLinkExists.RUnlock()
	return calls
}

// Store calls StoreFunc.
func (mock *ArticleStorageMock) Store(ctx context.Context, article model.Article) error {
	if mock.StoreFunc == nil {
		panic("ArticleStorageMock.StoreFunc: method is nil but ArticleStorage.Store was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Article model.Article
	}{
		Ctx:     ctx,
		Article: article,
	}
	mock.lockStore.Lock()
	mock.calls.Store = append(mock.calls.Store, callInfo)
	mock.lockStore.Unlock()
	return mock.StoreFunc(ctx, article)
}

// StoreCalls gets all the calls that were made to Store.
// Check the length with:
//
//	len(mockedArticleStorage.StoreCalls())
func (mock *ArticleStorageMock) StoreCalls() []struct {
	Ctx     context.Context
	Article model.Article
} {
	var calls []struct {
		Ctx     context.Context
		Article model.Article
	}
	mock.lockStore.RLock()
	calls = mock.calls.Store
	mock.lockStore.RUnlock()
	return calls
}
